### ISSUE TITLE
Arrow animation doesn't appear on medium screens

### ISSUE THREAD

**Issue by normade** [hackerinnen/hackerinnen#112]
I don't know if it was intended @Twissi but the arrow animation on the home page doesn't show up on my 13'' screen laptop.

**Comment by adrienluitot** [comment]
It's because in the css the arrow disappears for screen with height < 750px.
I think that it would be possible to decrease the size of the PULL animation, maybe only set 25px of difference between the begin and the end of the animation.
I think it would be better also to made the arrow coming back smoothly.
I can make a PR if you want ;)

**Comment by adrienluitot** [comment]
For example for extra small screens, it's possible to set the font-size to 20px and set bottom: 25px at 100% and 50px at 0%.
And then event for iPhone 5s it fits :D

**Comment by Twissi** [comment]
hey @adrienluitot, thanks for your help. Feel free to open a PR and I am happy to take look at it.
